"""Added tmp table for working with email confirmation

Revision ID: 1e6c5db71bb1
Revises: 92c5858a33b5
Create Date: 2024-10-24 14:02:41.247091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6c5db71bb1'
down_revision: Union[str, None] = '92c5858a33b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonvalid_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('account_created', sa.String(length=100), nullable=False),
    sa.Column('token_expires_at', sa.Integer(), nullable=False),
    sa.Column('token_hashed_value', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nonvalid_users_email'), 'nonvalid_users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nonvalid_users_email'), table_name='nonvalid_users')
    op.drop_table('nonvalid_users')
    # ### end Alembic commands ###
