"""removed column created at for tmp accounts

Revision ID: 554d38cb34b2
Revises: 1e6c5db71bb1
Create Date: 2024-10-24 16:44:59.017542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554d38cb34b2'
down_revision: Union[str, None] = '1e6c5db71bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nonvalid_users', 'account_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nonvalid_users', sa.Column('account_created', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
